name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  python:
    name: Test Python
    strategy:
      matrix:
        runner: [macos-latest]
        python: ["3.10"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda
        if: matrix.runner == 'macos-latest'
        run: |
          echo "Installing Miniconda..."
          curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Install our package in editable mode
        run: pip install -e .
      - name: Install dependencies 
        run: |
          echo "Installing dependencies..."
          pip install pytest==8.1.1 psycopg2-binary==2.9.9 -e .mlflow.repo
      - name: Run integration tests 20
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 21
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 22
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 23
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 24
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 25
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 26
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 27
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 28
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 29
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 210
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 211
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 212
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 31
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 32
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 33
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 34
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 35
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 36
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 37
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 38
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 39
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 310
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 311
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 312
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 320
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 321
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 322
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 323
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 324
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 325
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 326
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 327
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 328
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 329
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 3210
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 3211
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 3212
        run: |
          echo "Running integration tests with mage..."
          mage test:python
        - name: Run integration tests32123
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 31
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 32
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 33
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 34
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 35
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 36
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 37
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 38
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 39
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 310
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 311
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 312
        run: |
          echo "Running integration tests with mage..."
          mage test:python