name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  python:
    name: Test Python
    strategy:
      matrix:
        runner: [macos-13]
        python: ["3.10"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda
        if: matrix.runner == 'macos-13'
        run: |
          echo "Installing Miniconda..."
          curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Install our package in editable mode
        run: pip install -e .
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install pytest==8.1.1 psycopg2-binary==2.9.9 -e .mlflow.repo
      - name: Run integration tests
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 1
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 2
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 3
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 4
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 5
        run: |
          echo "Running integration tests with mage..."
          mage test:python
      - name: Run integration tests 6
        run: |
          echo "Running integration tests with mage..."
          mage test:python