name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  python:
    name: Test Python
    strategy:
      matrix:
        runner: [macos-13]
        python: ["3.10"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda
        if: matrix.runner == 'macos-latest'
        run: |
          echo "Installing Miniconda..."
          curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Initialize MLflow repo
        run: mage repo:init
      - name: Install our package in editable mode
        run: pip install -e .
      - name: Initialize MLflow repo
        run: mage repo:init
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install pytest==8.1.1 psycopg2-binary==2.9.9 -e .mlflow.repo
      - name: Check memory usage before pytest
        run: |
          echo "Checking memory usage before tests..."
          if command -v free > /dev/null; then
            free -m
          elif command -v vm_stat > /dev/null; then
            vm_stat
            echo "Free memory in MB:"
            vm_stat | awk '/Pages free/ { print $3 * 4096 / 1024 / 1024 " MB" }'
          elif command -v sysctl > /dev/null; then
            echo "Total memory in bytes:"
            sysctl hw.memsize
          else
            echo "Unable to determine memory usage on this system."
          fi
      - name: Enable Core Dumps
        run: |
          echo "Enabling core dumps for debugging..."
          ulimit -c unlimited || echo "ulimit not supported"
          sysctl -w kern.corefile=/cores/core.%P || echo "sysctl not supported"
      - name: Run integration tests
        run: |
          echo "Running integration tests with mage..."
          mage test:python
        continue-on-error: true
      - name: Check memory usage after pytest
        run: |
          echo "Checking memory usage after tests..."
          if command -v free > /dev/null; then
            free -m
          elif command -v vm_stat > /dev/null; then
            vm_stat
            echo "Free memory in MB:"
            vm_stat | awk '/Pages free/ { print $3 * 4096 / 1024 / 1024 " MB" }'
          elif command -v sysctl > /dev/null; then
            echo "Total memory in bytes:"
            sysctl hw.memsize
          else
            echo "Unable to determine memory usage on this system."
          fi
      - name: Collect Core Dumps
        if: failure()
        run: |
          echo "Checking for core dumps..."
          if ls /cores/core.* 1> /dev/null 2>&1; then
            echo "Core dumps found:"
            ls -lh /cores/core.*
          else
            echo "No core dumps found."
          fi
      - name: Debug pytest failures
        if: failure()
        run: |
          echo "Tests failed. Gathering debug information..."
          pytest --maxfail=5 --tb=short -vv
