name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  python:
    name: Test Python
    strategy:
      matrix:
        runner: [macos-latest]
        python: ["3.10"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda
        if: matrix.runner == 'macos-latest'
        run: |
          curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Initialize MLflow repo
        run: mage repo:init
      - name: Install our package in editable mode
        run: pip install -e .
      - name: Initialize MLflow repo
        run: mage repo:init
      - name: Install dependencies
        run: pip install pytest==8.1.1 psycopg2-binary==2.9.9 -e .mlflow.repo
      - name: Check memory usage before pytest
        run: free -m || vm_stat || systeminfo
      - name: Run integration tests
        run: mage test:python
        if: ${{ !(matrix.python == '3.12' && matrix.runner == 'windows-latest') }}
      - name: Check memory usage after pytest
        run: free -m || vm_stat || systeminfo
        
